### ISSUE TITLE
Document how to use this in typical CI runners

### ISSUE THREAD

**Issue by mattip** [EpicWink/proxpi#1]
This is great! Could you open a space in the README or other documentation to demonstrate using this in Ci runners like travis, azure pipelines, or github actions  which are used in many open source projects? The CI runner documentation about best practices with caching is not always clear: when a cache actually saves CI bandwidth and when it doesn't.

**Comment by EpicWink** [comment]
Sure, I'll get on it. An issue is running a persistent program on these runners: as far as I know, only BYO runners (where the user has full control over the server) can run these programs effectively

**Comment by mattip** [comment]
ahh, so this won't work with travis :( ?

**Comment by EpicWink** [comment]
Not unless you can use your own runners on Travis

**Comment by mattip** [comment]
OK, feel free to close this then.
