### ISSUE TITLE
ARM Docker image

### ISSUE THREAD

**Issue by ZuluPro** [EpicWink/proxpi#26]
Would it be possible to get Docker ARM images available ?
Currently, only amd64 is available giving  bad perfs (even 502) through emulation.

**Comment by nuvious** [comment]
I'm on it

**Comment by nuvious** [comment]
PR submitted. Screenshots of testing and dockerhub deployment in PR discussion.

**Comment by EpicWink** [comment]
For those who want them right now, nuvious has provided some ARM images (I can't test them myself): [nuvious/proxpi](https://hub.docker.com/r/nuvious/proxpi/tags).

I'm waiting for GitHub to provide ARM CI runners

**Comment by EpicWink** [comment]
ARM Docker images added with v1.2b0:

```shell
docker pull epicwink/proxpi:v1.2.0b0
```
