### ISSUE TITLE
flask dependency issue

### ISSUE THREAD

**Issue by kaibaesler** [EpicWink/proxpi#5]
A requirements.txt file stating the dependency on Flask>=2.0 is missing.

## Reproduction
1. Upgrade from a proxpi version 0.1.0 to 1.0.0 (with Flask 1.1.x installed) with `pip install --user -U proxpi`.
2. Restart the service
3. Navigate to the main page
4. Result: 500 internal server error and `TypeError: send_file() got an unexpected keyword argument 'max_age'` in the logs

## Environment
* `proxpi`: 1.0.0
* Python: 3.8+
* OS: Ubuntu 20.04
* `flask`: 1.1.x

## my 2 cents
First, let me thank you for publishing this useful little gem, your effort is much appreciated.

The culprit here is the API change that Flask did when switching to 2.x. I ran proxpi on top of the Ubuntu-provided python3-flask package, which was fine for proxpi 0.1.0, but now it seems that some keyword parameters have changed and that causes the TypeError.

IMHO the easiest (and clearest) fix would be to provide a requirements.txt file with the necessary dependencies.

BTW: I don not run proxpi in docker, I'm using a simple systemd service file, see below.

````
# /etc/systemd/system/pipcache.service
[Unit]
Description=proxpi pip cache
After=network.target

[Service]
Environment=FLASK_APP=proxpi.server FLASK_DEBUG=0 PYTHONUNBUFFERED=1
ExecStart=flask run --host=0.0.0.0

[Install]
WantedBy=multi-user.target
````

**Comment by aiudirog** [comment]
@kaibaesler The minimum version should be set here: https://github.com/EpicWink/proxpi/blob/master/setup.cfg#L22

**Comment by EpicWink** [comment]
I've added version constraints to the dependency requirements, but you may want to bin to `proxpi` v0.1 unless you can update your environment (ie install new versions of packages). Perhaps your service `ExecStart` can call a script which activates a virtual environment

**Comment by kaibaesler** [comment]
Thank you for the quick fix.

Regarding the virtual environment: yes, that's exactly what I did, `pipx install --include-deps flask && pipx inject --include-binaries --include-deps flask proxpi`. Works like a charm.
