### ISSUE TITLE
Support PIP_INDEX_URL finishing by /simple

### ISSUE THREAD

**Issue by mathben** [EpicWink/proxpi#56]
With the solution poetry-plugin-pypi-proxy with proxpi, https://github.com/chadac/poetry-plugin-pypi-proxy , we can use the proxy without modifying the pyproject.toml

Question : is it in the protocol to support with url /index/simple/PACKAGE ?

## Problem definition

But, poetry-plugin-pypi-proxy add `/simple` at the end of `PIP_INDEX_URL`. Causing error 
```
"GET /index/simple/typing-extensions/ HTTP/1.1" 404 207 0ms
```

When I did it manually with pip, it works
```
"GET /index/typing-extensions/ HTTP/1.1" 200 6488 8ms
```

## Current behaviour and workarounds

I configure `PIP_INDEX_URL=http://127.0.0.1:5000/index/`, it's not working. So I modify this library with this commit https://github.com/mathben/poetry-plugin-pypi-proxy/commit/307d38875a5da3ba8f86f9d9835bd4b479394b08 and it works!

## Proposed solution

Supported request finishing by /simple
Like http://localhost:5000/simple/ will do the same of http://localhost:5000/index/

Thanks for this project!

**Comment by EpicWink** [comment]
This is solely an issue with the Poetry plugin ([poetry-plugin-pypi-proxy](https://github.com/chadac/poetry-plugin-pypi-proxy)), as the environment variable `PIP_INDEX_URL` needs to have the same value whether using the Poetry plugin or using pip directly

```shell
$ export PIP_INDEX_URL=http://127.0.0.1:5000/index
$ pip install 'trimesh[easy]'
...
Successfully installed anyio-4.4.0 attrs-24.2.0 certifi-2024.8.30 chardet-5.2.0 colorlog-6.8.2 embreex-2.17.7.post5 exceptiongroup-1.2.2 h11-0.14.0 httpcore-1.0.5 httpx-0.27.2 idna-3.8 jsonschema-4.23.0 jsonschema-specifications-2023.12.1 lxml-5.3.0 manifold3d-2.5.1 mapbox-earcut-1.0.2 networkx-3.3 numpy-2.1.1 pillow-10.4.0 pycollada-0.8 python-dateutil-2.9.0.post0 referencing-0.35.1 rpds-py-0.20.0 rtree-1.3.0 scipy-1.14.1 shapely-2.0.6 six-1.16.0 sniffio-1.3.1 svg.path-6.3 trimesh-4.4.9 typing-extensions-4.12.2 vhacdx-0.0.8.post1 xatlas-0.0.9 xxhash-3.5.0
```

I suggest submitting a PR which makes adding the `simple/` path configurable, especially as most indexes don't host at `simple/`

<details><summary>Example PR diff (click to expand)</summary>

```diff
+        add_simple = (
+            os.environ.get("PLUGIN_NO_SIMPLE_SUFFIX", "").lower()
+            in ("", "0", "n", "no", "off", "false")
+        )
+
         # Add default repository
         poetry.pool.add_repository(
             LegacyProxyRepository(
-                name=proxy_id, url=f"{proxy_url}/simple/", config=poetry.config
+                name=proxy_id,
+                url=f"{proxy_url}/" + ("simple/" if add_simple else ""),
+                config=poetry.config,
             ),
             priority=Priority.DEFAULT,
         )
```

</details>

**Comment by mathben** [comment]
Where is define PLUGIN_NO_SIMPLE_SUFFIX ?

**Comment by EpicWink** [comment]
It's a new environment variable introduced by the PR, to be added to the plugin's documentation
