### ISSUE TITLE
Support Basic HTTP authentication

### ISSUE THREAD

**Issue by dsaydon90** [EpicWink/proxpi#7]
`pip` install supports Basic HTTP authentication: https://pip.pypa.io/en/stable/topics/authentication/#basic-http-authentication

example:
```
pip install -f https://user:pass@example.com:443/pkgs requests
```

It would be amazing if the `proxpi` will support it

**Comment by EpicWink** [comment]
If you mean accessing an index using HTTP basic-auth, `proxpi` already supports that. Just put the username and password (URL-encoded) in the basic-auth part of the URL, for example:
```
PROXPI_EXTRA_INDEX_URLS=https://user:pass%2Fword@pypi.example.com/index
```

---

If you mean using HTTP basic-auth to authenticate requests to the `proxpi` server, that's out of scope (feel free to make a pull-request, but I won't be supporting that use-case). `proxpi` is primarily designed to be run locally, not hosted on a server, so auth isn't necessary.

If you want to protect it, bring your own WSGI server which supports basic-auth (for example Apache with [mod_wsgi](https://fedingo.com/how-to-install-mod_wsgi-in-apache/) with [auth](https://httpd.apache.org/docs/current/howto/auth.html)), or if `proxpi` is hosted on a managed platform (eg Azure WebApp), use the provider's mechanism to protect the server with auth.

---

If you mean passing through auth credentials from user requests to `proxpi` to the index server, that's difficult to achieve with a cache: each user request to `proxpi` would require an auth-check request to the index server before responding to the user with the cached data. This would mostly defeat the purpose of the cache.
